sudo: false
language: scala
jdk:
  - openjdk8
scala:
  - 2.12.10
  - 2.13.1
script:
  - sbt ++$TRAVIS_SCALA_VERSION orgScriptCI
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION orgAfterCISuccess
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.coursier/cache"
    - "$HOME/.sbt"
before_install:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      openssl aes-256-cbc -K $encrypted_2da99c3b33cb_key -iv $encrypted_2da99c3b33cb_iv -in secret_key.asc.enc -out secret_key.asc -d;
      gpg --import --batch --passphrase "$PGP_PASSPHRASE" secret_key.asc;
    fi
